### ISSUE TITLE
Replace instance of model A in world with another model B from Asset Browser.

### ISSUE THREAD

**Issue by PeaceSells50** [nem0/LumixEngine#890] opened 2016-06-15 18:39 UTC
Optional:
1. Replace all instances of A.
2. Replace all selected instances of A.

**Comment by nem0** [comment] 2016-06-15 18:40
I knew I should not have removed that :)

**Comment by nem0** [comment] 2016-06-15 18:41
duplicate of #738

**Closed by nem0** 2016-06-15 18:41 UTC

**Comment by nem0** [comment] 2016-06-15 18:42
Note: it's also good to use https://github.com/nem0/LumixEngine/wiki/Entity-templates
